spring:
  profiles:
    active: dev     # 选用一个环境
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true       # 出现错误时, 直接抛出异常
  resources:
    add-mappings: false                             # 不要为资源文件建立映射
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8          # 东八区
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  config: classpath:spring-logback.xml

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8084  # 本地端口

mybatis-plus:
  global-config:
    db-config:
      id-type: INPUT    # 全局默认主键类型
      table-underline: false
  configuration:
    map-underscore-to-camel-case: false     # 是否开启自动驼峰命名规则（camel case）映射
    call-setters-on-nulls: true
